# Generated by Django 6.0.1 on 2026-01-13 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('api_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlsaber_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('connection_string', models.TextField()),
                ('memory', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlsaber_database_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_configs', to='sqlsaber.userapikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlsaber_model_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('database_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='sqlsaber.userdatabaseconnection')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='sqlsaber.usermodelconfig')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_database_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sqlsaber.userdatabaseconnection')),
                ('default_model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sqlsaber.usermodelconfig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sqlsaber_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('thinking', 'Thinking'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sqlsaber.thread')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='sqlsaber_me_thread__ac8003_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userapikey',
            index=models.Index(fields=['user', 'provider'], name='sqlsaber_us_user_id_b82fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='userapikey',
            index=models.Index(fields=['user', 'is_active'], name='sqlsaber_us_user_id_2fdd43_idx'),
        ),
        migrations.AddIndex(
            model_name='userdatabaseconnection',
            index=models.Index(fields=['user', 'name'], name='sqlsaber_us_user_id_3ea569_idx'),
        ),
        migrations.AddIndex(
            model_name='userdatabaseconnection',
            index=models.Index(fields=['user', 'is_active'], name='sqlsaber_us_user_id_1e2024_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdatabaseconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'name'), name='uniq_sqlsaber_user_db_connection_name_active'),
        ),
        migrations.AddIndex(
            model_name='usermodelconfig',
            index=models.Index(fields=['user', 'provider'], name='sqlsaber_us_user_id_fb2ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodelconfig',
            index=models.Index(fields=['user', 'display_name'], name='sqlsaber_us_user_id_bc8048_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodelconfig',
            index=models.Index(fields=['user', 'is_active'], name='sqlsaber_us_user_id_0c9cbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermodelconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'display_name'), name='uniq_sqlsaber_user_model_config_display_name_active'),
        ),
    ]
