# Generated by Django 6.0.1 on 2026-01-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlsaber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='thinking_level',
            field=models.CharField(choices=[('off', 'Off'), ('minimal', 'Minimal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('maximum', 'Maximum')], default='medium', max_length=10),
        ),
    ]
